{% set name = "anndata" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1efd7eb40839e0325bb066238280228a980d7dde6410793dbff2835f44a2d3ef

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python 

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core
    - setuptools_scm
    - pytoml
  run:
    - python >=3.6 
    - pandas >=0.23.0
    - scipy >=1.4
    - h5py
    - natsort
    - importlib_metadata  # [py<38]
    - packaging >=20
    - xlrd <2.0

test:
  imports:
    - anndata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theislab/anndata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: An annotated data matrix.
  description: |
    AnnData provides a scalable way of keeping track of data and learned annotations. 
    It was initially built for Scanpy (Genome Biology, 2018).
  doc_url: http://anndata.rtfd.io
  dev_url: https://github.com/theislab/anndata

extra:
  recipe-maintainers:
    - jakakokosar
    - pavlin-policar
    - flying-sheep
    - ivirshup
