travis:
  secure:
    BINSTAR_TOKEN: eb9OrxyEKX4VCtuktqpquutMMikM5SEB/yvrnVpi/+saYI/BrmWon4bztfexT0YA9ZRPIX9ivvffjXPAwE2dPe1xiNdlkU6pp23xk2aOfv3xy1gBtFPeI/rHPcFiJ26Jw6qIOJGBSEFSdG2K5kjy3eRU5DLBbsqgy+kedv62lMFkf9/hOiHDBZ6MIWGroucXWhJYwmSgMt3rGTgCA6+UAVB3jHQ/ohRnC1oOmXfJuvLW3ITVsL/1NUuO7X33v0tDqPEJsTkWdD2ZlpRD3unXCBQjdKFgNkkJke0HovmQusE19qwkgz3NP9iUBr7GPQztMLrswwCeUXzGW9MkIh9OkXduXWOp448dowsV2KW8WUI/Jm1prNMUSa2Wrp+biIgLQqd6ANTor8umM6aMNCughhhbSrtx75FTTWMWyVT9wvevrpmeXEd92YTynTduZM48kg9ykWD7lFLSn6qy7b52VHzYi2NEkPapakAXbdJ1r8/CJU40i77+6wd5ztzp3Q4F0Uw3D9r7FaCVNp0A6FSytv5Vxlq3Kc51YZ2YA93ygUq0ir3/Jhb+xszZOvXl60CdR4Nk8ig5UWy2fgD1oAj0Ou9/u9XG0ObAdHEW9LGWva/blAJGmvRayYcTOOppyKDkDh01BAib8soR2EEIN8jVOre9b6Z7c6ISShgir0FZiYY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
